#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


START = "# >>> opencode closed-network index ignore >>>"
END = "# <<< opencode closed-network index ignore <<<"

PATTERNS = [
    ".venv/",
    "venv/",
    "env/",
    "ENV/",
    "__pycache__/",
    "*.py[cod]",
    ".DS_Store",
    ".pytest_cache/",
    ".mypy_cache/",
    ".ruff_cache/",
    ".ipynb_checkpoints/",
    "node_modules/",
    "dist/",
    "build/",
    ".cache/",
    ".opencode/wsl/wheelhouse/",
    "**/.opencode/wsl/wheelhouse/",
    "*.whl",
    "*.tar.gz",
    "*.zip",
    "mlruns/",
    "mlartifacts/",
    "mlflow.db",
    "ai_studio/tracking/",
    "ai_studio/metrics/",
    "artifacts/",
    "model/",
    "models/",
    "saved_model/",
    "*.pt",
    "*.pth",
    "*.onnx",
    "*.h5",
    "*.keras",
    "*.pkl",
    "*.joblib",
    "*.safetensors",
]

TARGET_FILES = [".ignore", ".rgignore", ".gitignore"]


def managed_block() -> str:
    lines = [
        START,
        "# Generated by .opencode/scripts/apply_index_ignore.py",
        "# Speeds up OpenCode/file-tree scans in closed-network ML workspaces.",
        *PATTERNS,
        END,
        "",
    ]
    return "\n".join(lines)


def replace_or_append(text: str, block: str) -> tuple[str, str]:
    if START in text and END in text:
        before, rest = text.split(START, 1)
        _, after = rest.split(END, 1)
        return before.rstrip() + "\n\n" + block + after.lstrip("\n"), "updated"
    if text.strip():
        return text.rstrip() + "\n\n" + block, "appended"
    return block, "created"


def apply_file(path: Path, block: str, dry_run: bool) -> str:
    existing = path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""
    next_text, status = replace_or_append(existing, block)
    if next_text != existing and not dry_run:
        path.write_text(next_text, encoding="utf-8")
    if next_text == existing:
        return "unchanged"
    return status if not dry_run else f"would_{status}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply closed-network index ignore rules to a workspace.")
    parser.add_argument("--project", default=".", help="workspace root to update")
    parser.add_argument("--dry-run", action="store_true", help="show changes without writing files")
    args = parser.parse_args()

    project = Path(args.project).expanduser().resolve()
    if not project.exists():
        raise SystemExit(f"project not found: {project}")

    block = managed_block()
    print(f"Project: {project}")
    for name in TARGET_FILES:
        path = project / name
        status = apply_file(path, block, args.dry_run)
        print(f"{name}: {status}")

    print("\nIndex ignore targets:")
    for pattern in PATTERNS:
        print(f"- {pattern}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
